#!/bin/bash

gitconfig() {

    local USERNAME
    local EMAIL
    
    if [ ! -f "$HOME/.gitconfig" ]
    then 
        echo "Configuración de github"
        echo ""
        read -p "Indroduce tu usuario: " USERNAME
        git config --global user.name "${USERNAME}"
        read -p "Indroduce tu email: " EMAIL
        git config --global user.email "${EMAIL}"
        git config --global init.defaultBranch main
        git config --global core.editor vim
        git config --global pull.ff only
        git config --global pull.rebase true
        git config --global alias.lg "log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
        git config --global alias.s "status --short --branch"
    else
        dunstify "gitconfig file exit in home"
    fi
}

case $1 in 
    -g | --gitconfig )
        gitconfig
    ;;
    *)
        echo "No option"
    ;;
esac
