#!/bin/bash

installdotfiles() {
    
    local BASEDIR=$(dirname $0)
    cd $BASEDIR
    
    local FILESPATHS=$(find ./* -type f | \
    awk '{ gsub(/\.\//,""); print }' | \
    egrep "^config/(shell|vim\/vimrc)")
    
    local DIRSPATHS=$(find ./* -type d | \
    awk ' { gsub(/\.\//,""); print } ' | \
    sed -e "/local$/g; /config$/g; /config\/vim/g; /shell/g; /share$/g" | \
    grep "/*/")

    for path in $FILESPATHS
    do
        file=$(echo "$path" | cut -d '/' -f 3)
	[[ -f $HOME/.$file  ]] && \
	rm -r "$HOME/.$file" 2>/dev/null || \
	true

	ln -sd "$PWD/$path" "$HOME/.$file"
    done

    local WALLPAPER=$(find ./* -name wallpaper.png | \
    awk '{ gsub(/\.\//,""); print }') 
    
    [[ -f $HOME/.${WALLPAPER%.*} ]] && \
    rm "$HOME/.$WALLPAPER" 2>/dev/null || \
    true

    ln -sd "$PWD/$WALLPAPER" "$HOME/.${WALLPAPER%.*}"

    for path in $DIRSPATHS
    do
        #echo "$path"
	[[ -d $HOME/.$path ]] && \
	rm -r "$HOME/.$path" 2>/dev/null || \
	true

	ln -sd "$PWD/$path" "$HOME/.$path"
    done

    local VIMDOT=$(find ./* -type d | \
    awk '{ gsub(/\.\//,""); print }' | \
    egrep "vim")

    local VIM=$(echo $VIMDOT | cut -d '/' -f 2)

    [[ -d $HOME/.$VIM ]] && \
    rm "$HOME/.$VIM" 2>/dev/null || \
    true

    ln -sd "$PWD/$VIMFOLDER" "$HOME/.$VIM"

    xdotool key Super_L+Shift_R+r
}

uninstalldotfiles() {

    local BASEDIR=$(dirname $0)
    cd $BASEDIR

    local FILES=$(find ./* -type f | \
    awk '{ gsub(/\.\//,""); print }' | \
    egrep "^config/(shell|vim\/vimrc)" | \
    cut -d '/' -f 3)

    local DIRS=$(find ./* -type d | \
    awk '{ gsub(/\.\//,""); print }' | \
    sed -e "/local\/share/g; /config$/g; /config\/vim/g; /shell/g" | \
    grep "/*/")

    for file in $FILES
    do
        [[ -f $HOME/.$file ]] && \
        rm "$HOME/.$file" 2>/dev/null || true
    done

    for dir in $DIRS
    do
       [[ -d $HOME/.$dir ]] && \
       rm "$HOME/.$dir" 2>/dev/null || true
    done

    local WALLPAPER=$(find ./* -name wallpaper.png | \
    awk '{ gsub(/\.\//,""); print }') 
    
    [[ -f $HOME/.${WALLPAPER%.*} ]] | \
    rm "$HOME/.${WALLPAPER%.*}" 2>/dev/null || true

    local VIM=$(find ./* -type d | \
    awk '{ gsub(/\.\//,""); print }' | \
    egrep "vim" | cut -d '/' -f 2)

    [[ -d $HOME/.$VIM ]] && \
    rm "$HOME/.$VIM" 2>/dev/null || true

    [[ ! -d $HOME/.config/i3 ]] && i3-config-wizard 2>/dev/null || true

}

case $1 in

    -i | --install)
        installdotfiles
    ;;
    -u | --uninstall)
        uninstalldotfiles
    ;;
    *)
        echo "No option"
    ;;
esac
